/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardCollectsRouteImport } from './routes/dashboard.collects'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCollectsRoute = DashboardCollectsRouteImport.update({
  id: '/dashboard/collects',
  path: '/dashboard/collects',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/dashboard/admin/users',
  path: '/dashboard/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard/collects': typeof DashboardCollectsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard/collects': typeof DashboardCollectsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/register': typeof RegisterRoute
  '/workspace': typeof WorkspaceRoute
  '/dashboard/collects': typeof DashboardCollectsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/workspace'
    | '/dashboard/collects'
    | '/dashboard/'
    | '/dashboard/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/workspace'
    | '/dashboard/collects'
    | '/dashboard'
    | '/dashboard/admin/users'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/logout'
    | '/register'
    | '/workspace'
    | '/dashboard/collects'
    | '/dashboard/'
    | '/dashboard/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  RegisterRoute: typeof RegisterRoute
  WorkspaceRoute: typeof WorkspaceRoute
  DashboardCollectsRoute: typeof DashboardCollectsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/collects': {
      id: '/dashboard/collects'
      path: '/dashboard/collects'
      fullPath: '/dashboard/collects'
      preLoaderRoute: typeof DashboardCollectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/dashboard/admin/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  RegisterRoute: RegisterRoute,
  WorkspaceRoute: WorkspaceRoute,
  DashboardCollectsRoute: DashboardCollectsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
